"""Value objects representing typed identifiers used across the offboarding bounded context."""

from __future__ import annotations

from abc import ABC
from uuid import UUID, uuid4


class Id(ABC):
    """
    Abstract base class for IDs
    """
    __value: UUID
    
    def __init__(self, value: UUID | None = None) -> None:
        """
        Initializes the ID

        Args:
            value (UUID | None): the optional ID, if not passed, a random UUID is generated
        """
        if value is None:
            self.__value = uuid4()
        else:
            self.__value = value
        
    def get_id(self) -> UUID:
        """
        Returns the ID

        Returns:
            UUID: the current ID value.
        """
        return self.__value
    
    def set_id(self, id_value: UUID) -> None:
        """
        Sets the ID

        Args:
            id_value (UUID): the new ID
        """
        self.__value = id_value
        
    def regenerate_id(self) -> None:
        """
        Regenerates the ID
        """
        self.__value = uuid4()

    def is_equal(self, other: UUID | str | Id) -> bool:
        """
        Checks if two IDs are equal

        Args:
            other (UUID | str | Id): the other ID
        Returns:
            bool: whether the two IDs are equal
        """
        if isinstance(other, Id):
            return self.__value == other.get_id()
        elif isinstance(other, str):
            return self.__value == UUID(other)
        elif isinstance(other, UUID):
            return self.__value == other
        else:
            raise TypeError(f"Cannot compare Id with {type(other)}")

class ProcessId(Id):
    """
    Class representing a Process ID
    """

class OffboardingProcessId(ProcessId):
    """
    Class representing an Offboarding Process ID
    """


class InterviewId(Id):
    """Class representing an Interview ID"""


class DossierId(Id):
    """Class representing a Dossier ID"""


class ExternalUserId(ABC):
    """
    Abstract base class for external-system user identifiers (e.g. Slack user IDs).

    Unlike Id, these are opaque strings owned by an external system (Slack), not
    UUIDs generated by this backend, since employees and managers are not entities
    tracked in this backend's own database.
    """
    __value: str

    def __init__(self, value: str | None = None) -> None:
        """
        Initializes the identifier.

        Args:
            value (str | None): the external identifier (e.g. a Slack user ID). If
                not passed, a random UUID string is generated (used in tests where
                the exact value is irrelevant, only its uniqueness).
        """
        self.__value = value if value is not None else str(uuid4())

    def get_id(self) -> str:
        """
        Returns the identifier.

        Returns:
            str: the current identifier value.
        """
        return self.__value

    def set_id(self, id_value: str) -> None:
        """
        Sets the identifier.

        Args:
            id_value (str): the new identifier.
        """
        self.__value = id_value

    def is_equal(self, other: str | ExternalUserId) -> bool:
        """
        Checks if two identifiers are equal.

        Args:
            other (str | ExternalUserId): the other identifier.
        Returns:
            bool: whether the two identifiers are equal.
        """
        if isinstance(other, ExternalUserId):
            return self.__value == other.get_id()
        elif isinstance(other, str):
            return self.__value == other
        else:
            raise TypeError(f"Cannot compare ExternalUserId with {type(other)}")


class EmployeeId(ExternalUserId):
    """
    Class representing an Employee ID (an external Slack user ID)
    """


class ManagerId(ExternalUserId):
    """
    Class representing a Manager ID (an external Slack user ID)
    """
