"""baseline schema

Revision ID: e9b11d28972f
Revises: 
Create Date: 2026-07-10 13:22:31.698242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from app.infrastructure.persistence.models.sop import SOPS_CONTENT_FTS_INDEX_SQL


# revision identifiers, used by Alembic.
revision: str = 'e9b11d28972f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('manager_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('employee_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('manager_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("type IN ('offboarding')", name='ck_processes_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processes_employee_id'), 'processes', ['employee_id'], unique=False)
    op.create_table('sops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('origin_channel', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('interviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('process_id', sa.Uuid(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("state IN ('scheduled','in_progress','completed','cancelled')", name='ck_interviews_state'),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_id')
    )
    op.create_table('offboarding_processes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.CheckConstraint("state IN ('not_started','in_progress','pending_revision','finished','cancelled')", name='ck_offboarding_processes_state'),
    sa.ForeignKeyConstraint(['id'], ['processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sop_tags',
    sa.Column('sop_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['sop_id'], ['sops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sop_id', 'tag_id')
    )
    op.create_table('dossiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('process_id', sa.Uuid(), nullable=False),
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint("state IN ('not_generated','generating','draft','under_review','approved','cancelled')", name='ck_dossiers_state'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id'),
    sa.UniqueConstraint('process_id')
    )
    op.create_table('interview_turns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('turn_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('speaker_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('turn_order', sa.Integer(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sentiment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('answer_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint("speaker_role IN ('interviewer','interviewee')", name='ck_interview_turns_speaker_role'),
    sa.CheckConstraint("turn_type IN ('question','note')", name='ck_interview_turns_type'),
    sa.CheckConstraint('turn_order >= 0', name='ck_interview_turns_order_positive'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id', 'turn_order', name='uq_interview_turns_interview_order')
    )
    op.create_table('dossier_sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dossier_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section_order', sa.Integer(), nullable=False),
    sa.CheckConstraint("section_type IN ('responsibilities','contacts','pending_tasks','knowledge_areas')", name='ck_dossier_sections_type'),
    sa.CheckConstraint('section_order >= 0', name='ck_dossier_sections_order_positive'),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id', 'section_order', name='uq_dossier_sections_dossier_order')
    )
    op.create_table('section_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relationship', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_order', sa.Integer(), nullable=False),
    sa.CheckConstraint("email LIKE '%%@%%.%%'", name='ck_section_contacts_email_format'),
    sa.CheckConstraint('item_order >= 0', name='ck_section_contacts_order_positive'),
    sa.ForeignKeyConstraint(['section_id'], ['dossier_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_contacts_section_id'), 'section_contacts', ['section_id'], unique=False)
    op.create_table('section_knowledge_areas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expertise_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('item_order >= 0', name='ck_section_knowledge_areas_order_positive'),
    sa.ForeignKeyConstraint(['section_id'], ['dossier_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_knowledge_areas_section_id'), 'section_knowledge_areas', ['section_id'], unique=False)
    op.create_table('section_pending_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deadline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('item_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('item_order >= 0', name='ck_section_pending_tasks_order_positive'),
    sa.ForeignKeyConstraint(['section_id'], ['dossier_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_pending_tasks_section_id'), 'section_pending_tasks', ['section_id'], unique=False)
    op.create_table('section_responsibilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('item_order >= 0', name='ck_section_responsibilities_order_positive'),
    sa.ForeignKeyConstraint(['section_id'], ['dossier_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_responsibilities_section_id'), 'section_responsibilities', ['section_id'], unique=False)
    # ### end Alembic commands ###
    op.execute(SOPS_CONTENT_FTS_INDEX_SQL)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_sops_content_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_section_responsibilities_section_id'), table_name='section_responsibilities')
    op.drop_table('section_responsibilities')
    op.drop_index(op.f('ix_section_pending_tasks_section_id'), table_name='section_pending_tasks')
    op.drop_table('section_pending_tasks')
    op.drop_index(op.f('ix_section_knowledge_areas_section_id'), table_name='section_knowledge_areas')
    op.drop_table('section_knowledge_areas')
    op.drop_index(op.f('ix_section_contacts_section_id'), table_name='section_contacts')
    op.drop_table('section_contacts')
    op.drop_table('dossier_sections')
    op.drop_table('interview_turns')
    op.drop_table('dossiers')
    op.drop_table('sop_tags')
    op.drop_table('offboarding_processes')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('sops')
    op.drop_index(op.f('ix_processes_employee_id'), table_name='processes')
    op.drop_table('processes')
    # ### end Alembic commands ###
